name: Server Destruction

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  destroy-server:
    name: 'Destroy AWS EC2'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ID_ACCESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
